# Generated by Django 5.2.8 on 2025-12-12 07:06

import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=96)),
                ('last_name', models.CharField(max_length=96)),
                ('dob', models.DateField(validators=[racing.models.validate_dob])),
                ('registered_races', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=256, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team logo/', validators=[racing.models.validate_logo_size])),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceTrackName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('race_date', models.DateField()),
                ('registration_closure_date', models.DateField(blank=True, null=True)),
                ('registered_drivers', models.ManyToManyField(blank=True, related_name='races', to='racing.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='racing.team'),
        ),
    ]
