# Generated by Django 5.2.8 on 2025-12-13 16:02

import django.db.models.deletion
import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='race',
            name='city',
        ),
        migrations.RemoveField(
            model_name='race',
            name='country',
        ),
        migrations.RemoveField(
            model_name='race',
            name='registered_drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='racing.team'),
        ),
        migrations.AddField(
            model_name='race',
            name='trackLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='registered_races',
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', validators=[racing.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='driver',
            name='registered_races',
            field=models.ManyToManyField(blank=True, related_name='registere_drivers', to='racing.race'),
        ),
    ]
