# Generated by Django 5.2.8 on 2025-12-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_remove_driver_teams_remove_race_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='racing.team'),
            preserve_default=False,
        ),
    ]
