# Generated by Django 5.2.8 on 2025-12-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0004_alter_driver_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='registered_races',
            field=models.ManyToManyField(blank=True, related_name='registered_drivers', to='racing.race'),
        ),
    ]
