# Generated by Django 5.2.8 on 2025-12-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0007_alter_driver_registered_races'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='registered_races',
        ),
        migrations.AddField(
            model_name='race',
            name='registered_drivers',
            field=models.ManyToManyField(blank=True, related_name='registered_races', to='racing.driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='racing.team'),
        ),
    ]
