# Generated by Django 5.2.8 on 2025-12-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0008_remove_driver_registered_races_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='registered_drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='registered_races',
            field=models.ManyToManyField(blank=True, related_name='registered_drivers', to='racing.race'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='racing.team'),
        ),
    ]
