# Generated by Django 5.2.8 on 2025-12-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0009_remove_race_registered_drivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.race')),
            ],
        ),
    ]
